var title = [
  "Bridge Original",
  "City Listing",
  "Music Magazine",
  "Travel",
  "Alternative Band",
  "Fitness Tracker",
  "Photo App",
  "Virtual Reality",
  "Music Band",
  "Fast Food",
  "Exotic Travels",
  "Smartphone Store",
  "Makeup Artist",
  "Environmental Organization",
  "Organic Food Store",
  "Chocolate",
  "vCard",
  "Catering",
  "Delivery",
  "Fashion Store",
  "Designer Presentation",
  "Climbing Club",
  "Nail Salon",
  "Educational Center",
  "Pottery",
  "Beachwear Store",
  "Developer Portfolio",
  "Pizza Parlor",
  "Pop Music Magazine",
  "Boxing Gym",
  "Mountain Climbing",
  "Interactive Agency",
  "Book Landing",
  "Nurse Home",
  "TV Set Showcase",
  "Trendy Blog",
  "Photographer Portfolio",
  "Asian Cuisine",
  "Organic Market",
  "Gaming",
  "Jewelry",
  "Film Director",
  "Spa & Wellness",
  "Cryptocurrency",
  "Backpacks",
  "New Album Release",
  "Creative Office",
  "Urban Wear",
  "Ecology",
  "Jazz Club",
  "Dron Studio",
  "Matcha",
  "Floristry",
  "Water Plant",
  "University III",
  "Wristwatch Shop",
  "Pet Shop",
  "Kids Fashion",
  "Digital Studio",
  "Web Hosting",
  "Kindergarten",
  "Gardening",
  "Creative Studio",
  "Gift Shop",
  "Tiles",
  "Tech Support",
  "Jewelry Store",
  "Bicycle Shop",
  "Tattoo Studio",
  "Musician",
  "Language School",
  "Recipes",
  "Animal Shelter",
  "Human Resources",
  "Freelancer Portfolio",
  "Tailor",
  "Sushi Bar",
  "Metro Blog",
  "Golf",
  "Gym",
  "Handicraft",
  "Running",
  "Business Consulting",
  "Loan Company",
  "Laundry Service",
  "3D Modeling",
  "Casino",
  "Art Gallery",
  "Airline",
  "Laboratory",
  "Law Office",
  "Software Development",
  "Wildlife",
  "IT conference",
  "Web Studio",
  "Craft Beer Bar",
  "Fitness",
  "Bar",
  "Architectural Firm",
  "Bike Rental",
  "Designer Expo",
  "Barber Shop",
  "Dental Clinic",
  "Horse Riding",
  "Nutritionist",
  "Candidate",
  "Renewable Energy",
  "Explorer",
  "Medical",
  "Wedding Invitation",
  "Movie",
  "NGO",
  "Wedding Invitation Card",
  "Recording Studio",
  "Psychotherapy",
  "Nightclub",
  "Interior Decor",
  "Hi-Fi",
  "Tea",
  "Burger Place",
  "Frozen Yogurt",
  "Museum",
  "Optician",
  "Pole Dance",
  "Mountain Biking",
  "Video Production",
  "Soap",
  "Italian Restaurant",
  "Music Festival",
  "Coworking Space",
  "Technology",
  "Temple",
  "Agriculture",
  "Startup Company",
  "Florist",
  "Urban Dance",
  "Vineyard",
  "Writer",
  "Fullscreen Shop",
  "Restaurant And Bar",
  "Moving Company",
  "Beauty Center",
  "Creative Blog",
  "Agency Minimal",
  "App Presentation",
  "Winter Sports",
  "Chequered Blog",
  "Hair Salon",
  "Startup Summit",
  "Furniture Shop",
  "Modern Photography",
  "Tech Showcase",
  "Resume",
  "Bakery",
  "Headlines Blog",
  "Smoothie Bar",
  "Fashion Blog",
  "Babysitter",
  "Portfolio With Left Menu",
  "Catalog",
  "Photo Slider",
  "Vibrant Portfolio",
  "Yoga Studio",
  "Fashion Photography",
  "Factory",
  "Beer Showcase",
  "Running Club",
  "Yoga Center",
  "UI Design Company",
  "Design Studio",
  "Masonry Shop",
  "Digital Startup",
  "App Launch",
  "Pets",
  "Charity",
  "Sportswear",
  "Vacation Rental",
  "Conference",
  "Summer Shop",
  "Tech Blog",
  "Crossfit",
  "Modern Furniture",
  "Freelancer",
  "Urban Fashion",
  "Left Menu Initially Hidden",
  "Photography Parallax",
  "Paper",
  "Urban Shop",
  "Chocolaterie",
  "Interior Decoration",
  "Dentist",
  "Rock Band",
  "Startup",
  "Child Care",
  "Wedding Planner",
  "Illustrator Portfolio",
  "Leather Shop",
  "Modern Restaurant",
  "Spa Center",
  "Biker Club",
  "Plumber",
  "Tiled Shop",
  "Online Agency",
  "One Page",
  "SEO Company",
  "Craftsman",
  "Orchestra",
  "Cafe",
  "Modern Blog",
  "Boutique",
  "Bicycle Brand",
  "Digital",
  "Contemporary Art",
  "Designer Portfolio",
  "3D Artist",
  "Fashion Agency",
  "UX/UI Design",
  "App Showcase",
  "Small Brand",
  "Illustrator",
  "Fashion",
  "Bauhaus",
  "Minimal Shop",
  "Law Firm",
  "Developer",
  "Clean Energy",
  "Animals",
  "Fashion Shop",
  "Mosque",
  "Jeans",
  "Jazz Bar",
  "Wedding Announcement",
  "Financial Business",
  "Lifestyle Blog",
  "Masonry Gallery",
  "Creative Vintage",
  "Transport",
  "Flat Company",
  "Avenue",
  "Photography Tiles",
  "Urban Store",
  "Black–And–White",
  "Pet Sanctuary",
  "Skater",
  "Maintenance Mode",
  "Innovation",
  "Hipster Agency",
  "Business Conference",
  "Portfolio Masonry",
  "Video Slider",
  "Flat",
  "Furniture",
  "Life Coach",
  "Mist",
  "Urban",
  "Grid",
  "Blog Loop",
  "Communication",
  "Case Study",
  "Standard",
  "Skin Care",
  "Coming Soon Simple",
  "Campaign",
  "Simple Blog",
  "Blog With Slider",
  "Dim Sum",
  "Blog In Grid",
  "Left Menu",
  "Modern",
  "Outdoors",
  "Dark Parallax",
  "Portfolio Pinterest",
  "Wireframe",
  "Photographer",
  "Architecture",
  "Creative",
  "Photography  Split Screen",
  "Agency One Page",
  "Wellness",
  "Wedding",
  "Brewery",
  "Creative Photography",
  "Vertical Menu",
  "Elegant Slider",
  "Full Screen Sections",
  "Shop Grid",
  "Portfolio Pinterest Style",
  "Portfolio",
  "Travel Blog",
  "Restaurant",
  "Business Report",
  "Construction Showcase",
  "Business",
  "Consulting",
  "Creative Agency",
  "Construction Company",
  "Freelance Designer",
  "Clothing Store",
  "Product Showcase",
  "Estate",
  "Health Blog",
  "Bar & Grill",
  "Minimalist",
  "Watch Store",
  "Football",
  "Designer Personal",
  "Attorney",
  "Air",
  "Barber",
  "Skate Shop",
  "Sunglasses Shop",
  "Angled Sections",
  "Digital Agency",
  "Short Slider",
  "Architect Studio",
  "Artist Portfolio",
  "Branding",
  "Collection",
  "CV",
  "Handmade",
  "Photography Portfolio",
  "Creative Business",
  "Pinterest Blog",
  "Simple Photography",
  "Cupcake",
  "Health",
  "Jazz",
  "Hosting",
  "Split Screen",
  "University",
  "Minimal Blog",
  "Parallax",
  "Studio",
  "Contemporary Company",
  "Left Menu with Image",
  "Kids",
  "Graphic Studio",
  "Interior Design",
  "Organic",
  "Travel Agency",
  "Rustic",
  "Light",
  "Minimal",
  "Telecom",
  "Urban Studio",
  "Web Agency",
  "Shop With Left Menu",
  "Business Consultant",
  "Construction",
  "Corporate",
  "Shop Wide",
  "Coming Soon Creative",
  "One Page Site",
  "Office",
  "Modern Business",
  "Dark Border",
  "Blog Slider",
  "Lawyer",
  "Cargo",
  "Marine",
  "Company",
  "Passepartout",
  "Photo Gallery",
  "Agency",
  "Vintage",
  "Winery",
  "Denim",
  "Car Dealership",
  "Corporation",
  "Blog Pinterest Style",
  "Advertising Agency",
  "Nature Blog",
  "Photo Studio",
  "Global Business",
  "Church",
  "University II"
];

var subtitle = [
  "Business",
  "Business",
  "Blog",
  "Business",
  "Business",
  "Business",
  "Business&nbsp;|&nbsp;Creative",
  "Business",
  "Business",
  "Business",
  "Business",
  "Business&nbsp;|&nbsp;Shop",
  "Business",
  "Business",
  "Business&nbsp;|&nbsp;Shop",
  "Business",
  "Creative&nbsp;|&nbsp;Portfolio",
  "Business",
  "Business",
  "New&nbsp;|&nbsp;Shop",
  "Creative",
  "Business",
  "Business",
  "Business",
  "Business&nbsp;|&nbsp;Creative",
  "New&nbsp;|&nbsp;Shop",
  "Business&nbsp;|&nbsp;Portfolio",
  "Business",
  "Blog",
  "Business",
  "Creative",
  "Business",
  "Business&nbsp;|&nbsp;Creative",
  "Business",
  "Business",
  "Blog",
  "Creative&nbsp;|&nbsp;Portfolio",
  "Business&nbsp;|&nbsp;Creative",
  "Business&nbsp;|&nbsp;One Page",
  "Creative",
  "Business",
  "Creative&nbsp;|&nbsp;Portfolio",
  "Business",
  "Business",
  "Business",
  "Business",
  "Business",
  "Business&nbsp;|&nbsp;Shop",
  "Creative&nbsp;|&nbsp;Other",
  "Creative",
  "Creative",
  "Business",
  "Creative",
  "Business",
  "Business",
  "Creative&nbsp;|&nbsp;Shop",
  "Business",
  "New&nbsp;|&nbsp;Shop",
  "Business&nbsp;|&nbsp;Creative",
  "Business",
  "Business",
  "Business",
  "Business&nbsp;|&nbsp;One Page",
  "Creative&nbsp;|&nbsp;Shop",
  "Business",
  "Business",
  "New&nbsp;|&nbsp;Shop",
  "Creative",
  "Business",
  "Business&nbsp;|&nbsp;Creative",
  "Business&nbsp;|&nbsp;Other",
  "Blog",
  "Business&nbsp;|&nbsp;Creative",
  "Business",
  "Creative&nbsp;|&nbsp;Portfolio",
  "Business",
  "Business",
  "Blog",
  "Business",
  "Business",
  "Creative",
  "Business",
  "Business",
  "Business",
  "Business",
  "Creative",
  "Business",
  "Blog&nbsp;|&nbsp;Creative",
  "Business",
  "Business",
  "Business",
  "Business",
  "Creative",
  "Business",
  "Business&nbsp;|&nbsp;Creative",
  "Business",
  "Business",
  "Business&nbsp;|&nbsp;Creative",
  "Business&nbsp;|&nbsp;Creative",
  "Business",
  "Business&nbsp;|&nbsp;Creative",
  "Business",
  "Business",
  "Business",
  "Business",
  "Business",
  "Business",
  "Blog",
  "Business",
  "New",
  "Business",
  "Business",
  "Business&nbsp;|&nbsp;Creative&nbsp;|&nbsp;One Page",
  "Creative",
  "Business",
  "Business&nbsp;|&nbsp;Creative",
  "Business&nbsp;|&nbsp;Creative",
  "Creative",
  "New&nbsp;|&nbsp;Shop",
  "Business",
  "Creative",
  "Creative",
  "New&nbsp;|&nbsp;Shop",
  "Creative",
  "New",
  "Creative&nbsp;|&nbsp;One Page",
  "Creative&nbsp;|&nbsp;Shop",
  "Business",
  "Business&nbsp;|&nbsp;Creative",
  "Business",
  "Business&nbsp;|&nbsp;Creative",
  "New",
  "Business&nbsp;|&nbsp;Other",
  "Business&nbsp;|&nbsp;Creative",
  "Business",
  "Business",
  "Business",
  "Business",
  "Creative&nbsp;|&nbsp;Shop",
  "Business",
  "Business",
  "Business",
  "Blog",
  "Business&nbsp;|&nbsp;Creative",
  "Business&nbsp;|&nbsp;Creative&nbsp;|&nbsp;One Page",
  "Business",
  "Blog",
  "Business",
  "Business",
  "Shop",
  "Creative&nbsp;|&nbsp;Portfolio",
  "Creative&nbsp;|&nbsp;One Page",
  "Business&nbsp;|&nbsp;Creative&nbsp;|&nbsp;One Page&nbsp;|&nbsp;Portfolio",
  "Business",
  "Blog",
  "Business",
  "Blog",
  "Business",
  "Creative&nbsp;|&nbsp;Other&nbsp;|&nbsp;Portfolio",
  "Business",
  "Creative&nbsp;|&nbsp;Other&nbsp;|&nbsp;Portfolio",
  "Creative&nbsp;|&nbsp;Portfolio",
  "Business",
  "Creative&nbsp;|&nbsp;Portfolio",
  "Business",
  "Business&nbsp;|&nbsp;One Page",
  "Business",
  "Business",
  "Business&nbsp;|&nbsp;Creative&nbsp;|&nbsp;One Page",
  "Business&nbsp;|&nbsp;Creative",
  "Creative&nbsp;|&nbsp;Shop",
  "Business",
  "Business&nbsp;|&nbsp;Creative",
  "Business",
  "Business",
  "Business&nbsp;|&nbsp;Shop",
  "Business&nbsp;|&nbsp;One Page",
  "Business&nbsp;|&nbsp;Creative&nbsp;|&nbsp;One Page",
  "Shop",
  "Blog",
  "Business",
  "One Page&nbsp;|&nbsp;Shop",
  "Creative&nbsp;|&nbsp;Portfolio",
  "Business",
  "Creative&nbsp;|&nbsp;Other&nbsp;|&nbsp;Portfolio",
  "Creative",
  "Business&nbsp;|&nbsp;Creative",
  "Shop",
  "Business&nbsp;|&nbsp;Creative",
  "Business&nbsp;|&nbsp;Creative&nbsp;|&nbsp;Shop",
  "Business",
  "Creative",
  "Creative&nbsp;|&nbsp;Portfolio",
  "Business&nbsp;|&nbsp;One Page",
  "Business",
  "Creative&nbsp;|&nbsp;Portfolio",
  "Business&nbsp;|&nbsp;Creative&nbsp;|&nbsp;Shop",
  "Business",
  "Business",
  "Business&nbsp;|&nbsp;Creative&nbsp;|&nbsp;One Page",
  "Business",
  "Shop",
  "Business&nbsp;|&nbsp;Creative",
  "Business&nbsp;|&nbsp;Creative&nbsp;|&nbsp;One Page",
  "Business",
  "Business",
  "Business",
  "Business",
  "Blog",
  "Shop",
  "Business&nbsp;|&nbsp;One Page",
  "Business&nbsp;|&nbsp;Creative&nbsp;|&nbsp;Portfolio",
  "Creative&nbsp;|&nbsp;Portfolio",
  "Creative&nbsp;|&nbsp;Portfolio",
  "Creative&nbsp;|&nbsp;Portfolio",
  "Business&nbsp;|&nbsp;Creative&nbsp;|&nbsp;One Page",
  "Business&nbsp;|&nbsp;Creative&nbsp;|&nbsp;One Page",
  "Business&nbsp;|&nbsp;One Page",
  "Business&nbsp;|&nbsp;Creative",
  "Creative&nbsp;|&nbsp;Portfolio",
  "Business&nbsp;|&nbsp;Creative",
  "Creative&nbsp;|&nbsp;Portfolio",
  "Business&nbsp;|&nbsp;Creative&nbsp;|&nbsp;Shop",
  "Business",
  "Creative&nbsp;|&nbsp;One Page",
  "Business",
  "Business",
  "Shop",
  "Other",
  "Shop",
  "Creative&nbsp;|&nbsp;One Page",
  "Business",
  "Business",
  "Blog",
  "Creative&nbsp;|&nbsp;Other&nbsp;|&nbsp;Portfolio",
  "Business&nbsp;|&nbsp;Creative",
  "Business",
  "Business",
  "One Page",
  "Creative&nbsp;|&nbsp;Portfolio",
  "Shop",
  "Creative",
  "Business",
  "Business&nbsp;|&nbsp;Creative",
  "Business&nbsp;|&nbsp;One Page",
  "Business&nbsp;|&nbsp;Creative",
  "Business&nbsp;|&nbsp;Creative&nbsp;|&nbsp;Portfolio",
  "Business",
  "Creative&nbsp;|&nbsp;Portfolio",
  "Business&nbsp;|&nbsp;Creative&nbsp;|&nbsp;Other&nbsp;|&nbsp;Portfolio",
  "Business&nbsp;|&nbsp;Creative&nbsp;|&nbsp;One Page",
  "Business",
  "Business",
  "Creative&nbsp;|&nbsp;Portfolio",
  "Business&nbsp;|&nbsp;Creative",
  "Business&nbsp;|&nbsp;Other&nbsp;|&nbsp;Shop",
  "Blog&nbsp;|&nbsp;Other",
  "Business",
  "Creative&nbsp;|&nbsp;Portfolio",
  "Business&nbsp;|&nbsp;Creative&nbsp;|&nbsp;Other",
  "Business",
  "Business&nbsp;|&nbsp;One Page",
  "Business",
  "Blog&nbsp;|&nbsp;Creative",
  "Blog&nbsp;|&nbsp;Other",
  "Business",
  "Blog&nbsp;|&nbsp;Other",
  "Business&nbsp;|&nbsp;Creative",
  "Business&nbsp;|&nbsp;Creative",
  "Creative&nbsp;|&nbsp;One Page",
  "Creative&nbsp;|&nbsp;Portfolio",
  "Creative&nbsp;|&nbsp;Portfolio",
  "Business&nbsp;|&nbsp;Other",
  "Creative&nbsp;|&nbsp;Portfolio",
  "Business&nbsp;|&nbsp;Creative",
  "Creative&nbsp;|&nbsp;Portfolio",
  "Creative",
  "Business&nbsp;|&nbsp;Creative&nbsp;|&nbsp;One Page",
  "Business",
  "Business",
  "Business",
  "Creative&nbsp;|&nbsp;Portfolio",
  "Business&nbsp;|&nbsp;Creative&nbsp;|&nbsp;Other",
  "Blog&nbsp;|&nbsp;Business&nbsp;|&nbsp;Other",
  "Creative&nbsp;|&nbsp;Other",
  "Other&nbsp;|&nbsp;Shop",
  "Creative&nbsp;|&nbsp;Other&nbsp;|&nbsp;Portfolio",
  "Creative&nbsp;|&nbsp;Portfolio",
  "Blog",
  "Business",
  "Business",
  "Business",
  "Business",
  "Business",
  "Business&nbsp;|&nbsp;Creative",
  "Business",
  "Creative&nbsp;|&nbsp;Portfolio",
  "Business&nbsp;|&nbsp;Creative&nbsp;|&nbsp;Shop",
  "Business&nbsp;|&nbsp;One Page&nbsp;|&nbsp;Shop",
  "Business",
  "Blog",
  "Business",
  "Business&nbsp;|&nbsp;Creative",
  "Business&nbsp;|&nbsp;Shop",
  "Business",
  "Creative&nbsp;|&nbsp;Portfolio",
  "Business",
  "Business&nbsp;|&nbsp;Creative",
  "Business&nbsp;|&nbsp;One Page",
  "Shop",
  "Shop",
  "Business&nbsp;|&nbsp;Creative&nbsp;|&nbsp;Other",
  "Business&nbsp;|&nbsp;Creative",
  "Business&nbsp;|&nbsp;Creative&nbsp;|&nbsp;Other",
  "Business&nbsp;|&nbsp;Creative&nbsp;|&nbsp;Portfolio",
  "Creative&nbsp;|&nbsp;Portfolio",
  "Business&nbsp;|&nbsp;Creative",
  "Business&nbsp;|&nbsp;Portfolio",
  "Creative&nbsp;|&nbsp;Portfolio",
  "Shop",
  "Creative&nbsp;|&nbsp;Portfolio",
  "Business&nbsp;|&nbsp;Creative",
  "Blog&nbsp;|&nbsp;Creative",
  "Business&nbsp;|&nbsp;Creative",
  "Business&nbsp;|&nbsp;Creative",
  "Business",
  "Creative",
  "Business&nbsp;|&nbsp;One Page",
  "Other",
  "Business",
  "Blog",
  "Business&nbsp;|&nbsp;One Page",
  "Business&nbsp;|&nbsp;Creative",
  "Business",
  "Business&nbsp;|&nbsp;Creative&nbsp;|&nbsp;Other",
  "Business",
  "Business&nbsp;|&nbsp;Creative",
  "Business&nbsp;|&nbsp;Creative",
  "Business",
  "Business&nbsp;|&nbsp;Creative",
  "Business&nbsp;|&nbsp;Creative",
  "Business",
  "Creative&nbsp;|&nbsp;Portfolio",
  "Business",
  "Business&nbsp;|&nbsp;Creative&nbsp;|&nbsp;Portfolio",
  "Business",
  "Other&nbsp;|&nbsp;Shop",
  "Business",
  "Business&nbsp;|&nbsp;One Page",
  "Business",
  "Other&nbsp;|&nbsp;Shop",
  "Business&nbsp;|&nbsp;Creative&nbsp;|&nbsp;One Page",
  "Business&nbsp;|&nbsp;Creative&nbsp;|&nbsp;One Page&nbsp;|&nbsp;Other",
  "Business",
  "Business",
  "Business&nbsp;|&nbsp;Creative&nbsp;|&nbsp;Other",
  "Blog",
  "Business",
  "Business",
  "Business&nbsp;|&nbsp;Shop",
  "Business",
  "Business&nbsp;|&nbsp;Creative",
  "Creative&nbsp;|&nbsp;Portfolio",
  "Business&nbsp;|&nbsp;Creative",
  "Business&nbsp;|&nbsp;Creative&nbsp;|&nbsp;Portfolio",
  "Business",
  "Creative&nbsp;|&nbsp;Portfolio",
  "Business",
  "Business",
  "Blog&nbsp;|&nbsp;Other",
  "Business&nbsp;|&nbsp;Creative",
  "Blog",
  "Creative&nbsp;|&nbsp;Portfolio",
  "Business",
  "Other",
  "Business"
];


var demoContainer = document.getElementById('demon-container');

for (var i = 0; i < images.length; i++) {
  //images[i]
  demoContainer.innerHTML += `
    <div class="one-demo">
      <img src="${images[i]}" alt="">
      <div class="one-demo-title">
        ${title[i]}
      </div>
      <div class="one-demo-subtitle">
        ${subtitle[i]}
      </div>
    </div>`
}
